devtools::load_all()
obj = mboServiceConnect("http://localhost:5000")
data = data.frame(x = c(5,10), y = c(20,30))
mboServiceSetConfigKeyRaw(obj, "par.set", "{}")
mboServiceUpload(obj, data)
point = mboServicePropose(obj)
print(point)
mboServiceDisconnect(obj)
